name: styled_text
description: Text widget with formatted text using tags. Makes it easier to use formatted text in multilingual applications.
version: 8.0.0
author: Andy Chentsov <chentsov@gmail.com>
homepage: https://github.com/andyduke/styled_text_package/tree/master/styled_text
repository: https://github.com/andyduke/styled_text_package
issue_tracker: https://github.com/andyduke/styled_text_package/issues

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
